POST http://localhost:5069/breakfasts
Content-Type: application/json

{
    "name": "V",
    "description": "sd",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###

GET http://localhost:5069/breakfasts/ef6aed9e-1bbd-44bc-bfb7-244512533796